### ISSUE TITLE
Cannot view token on exchange 

### ISSUE THREAD

**Issue by tmpce** [bokkypoobah/TokenTrader#10]
I just created a TokenTrader contract and CryptoDerivatives is now picking it up. 

It's called The Most Private Coin Ever. 

I see that because the symbol is "???" it is not allowing a click-through since I'm assuming the URL cannot parse it correctly. 

Here's the link: https://cryptoderivatives.market/token/???

**Comment by bokkypoobah** [comment]
I'll try to fix this over the next few days.

**Comment by tmpce** [comment]
Cool, thank you!

**Comment by jet86** [comment]
You can view the page at https://cryptoderivatives.market/token/%3F%3F%3F but the API isn't encoding the "?" either, so it's still not returning the data which you can get manually at https://cryptoderivatives.market/api/token/%3F%3F%3F

**Comment by bokkypoobah** [comment]
I've renamed the symbol to "PRIVATE" so it should now work.
