### ISSUE TITLE
Volume of cryptoderivatives is not showing on coinmarketcap.com

### ISSUE THREAD

**Issue by Bingo123123123** [bokkypoobah/TokenTrader#11]
Here is an example:
https://coinmarketcap.com/assets/ethereum-movie-venture/#markets
there is a ? at the volume of cryptoderivatives.market, it worked fine until yesterday.

**Comment by bokkypoobah** [comment]
Seems to be working now. There was a hiccup with the disk space one of the servers but this was fixed several days ago.
