### ISSUE TITLE
SWT is sometimes referred to as SWM 

### ISSUE THREAD

**Issue by BvL13** [bokkypoobah/TokenTrader#2]
Hi Bookkypoobah,
your wiki covers the SWT as well. In the text though it is sometimes referred to as SWM, which is not correct. It is called SWT = SWarm city Token
It would be great if you could make the proper ammendments.
Thank you.

Bernd

**Comment by bokkypoobah** [comment]
Corrected. Please check.

**Comment by BvL13** [comment]
Checked it. Now it's perfect. Thank you very much.

**Comment by bokkypoobah** [comment]
Great!
