### ISSUE TITLE
Name error on https://github.com/bokkypoobah/TokenTrader/wiki/LOVE-%E2%80%90-I-Love-You

### ISSUE THREAD

**Issue by decentralizedlove** [bokkypoobah/TokenTrader#6]
https://github.com/bokkypoobah/TokenTrader/wiki/LOVE-%E2%80%90-I-Love-You

Token Contract Information have an error, name say: Ethereum Movie Venture

Name is: I Love You

Regards

**Comment by bokkypoobah** [comment]
Updated. Please check.
