### ISSUE TITLE
Trades are not registed neither in activity nor in the API

### ISSUE THREAD

**Issue by Bingo123123123** [bokkypoobah/TokenTrader#7]
Since june 13th the EMV trades are somehow not registered, here is a transaction that has worked but is not registered neither in the activity tab nor on the API
https://etherscan.io/tx/0xd08e7ab8b96d824259b8e60b6408796e9cc2accfca618f05fe0e67de36c3216e

**Comment by bokkypoobah** [comment]
Looking into this, thanks.

**Comment by bokkypoobah** [comment]
Fixed now. It was a server memory issue, started working after I doubled the memory.

**Comment by Bingo123123123** [comment]
thank you so much!
have a nice day!



Am 15.06.2017 um 01:34 schrieb BokkyPooBah:
